name: TEST WEB API AUTOMATION JAVA CAPSTONE PROJECT
name: Rest API

on:
  push:
@@ -26,26 +26,4 @@ jobs:
    steps:
      - uses: actions/checkout@v3
      - name: Test API III new branch
        run: mvn clean verify
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test API Capstone Project
        run: |
          cd CICD-Pipeline-Capstone Project
          mvn verify
          working-directory: ./CICD-Pipeline-CapstoneProject
        run: mvn clean verify
