<<<<<<< HEAD
name: Rest API
=======
name: TEST WEB API AUTOMATION JAVA CAPSTONE PROJECT
>>>>>>> d531f900c3bffb54aad77f4c373334fad0e14f39

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
<<<<<<< HEAD
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
  test:
    name: Test API II
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test API III new branch
        run: mvn clean verify
=======
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test API Capstone Project
        run: |
          cd CICD-Pipeline-Capstone Project
          mvn verify
          working-directory: ./CICD-Pipeline-CapstoneProject

        working-directory: C:\\Users\\VICTUS\\IdeaProjects\\RestAssuredCapstoneProject
>>>>>>> d531f900c3bffb54aad77f4c373334fad0e14f39
